### PR TITLE
Changed fork licence

### PR DESCRIPTION
**Pull request by jaykay99992**
Changed the LGPL license to MIT to allow more flexibility

### CODE REVIEW

**Comment by edgarogh** [comment]
Hello,

IANAL but just to save you from legal troubles, changing the license from LGPL to MIT is illegal, unless you have the explicit permission from every contributor of the original code. LGPL is a viral license and every bit of code that is based on LGPL (including forks of LGPL-licensed code) has to be licensed under LGPL or a more restrictive license.

The following chart shows you license compatibility; arrows from A to B indicate that you can relicense code under license A to a license B. Note how MIT can be relicensed as LGPL, but not the contrary.

**Comment by jaykay99992** [comment]
@edgarogh Oh, thank you for the remark, should I just reject the pull request then ?

**Comment by edgarogh** [comment]
You should indeed, as merging it would put you in legal trouble.

**Comment by jaykay9999** [comment]
Pull request rejected due to possible legal issues.

**Pull request closed without merging**
