### PR TITLE
reduced number of declared variables

### PR DESCRIPTION
**Pull request by jaykay99992**
I combined the following variables in one array passed to createRadialGradient() instead of passing each variable independently.      
      
      double cx,
      double cy,
      double fx,
      double fy,
      double r,
      
      
      To facilitate the management of parameters.

### CODE REVIEW

**Comment by edgarogh** [comment]
Hello,

I'm not sure I understand the rationale behind this change and how boxing all parameters in an array would "facilitate the management of parameters". It also comes with a few disadvantages over independent parameters:

  * It shifts length checks to runtime: previously, your code wouldn't have compiled if you missed a parameter, and now, it would compile but throw an `IndexOutOfBoundsException` during runtime. You can also pass an array which is too large, which could be intentional in some very rare cases, but would more likely be a human error.
  * In the end, in both call sites, you still end up having to construct the array before giving it to the function, so it uses even more characters than before
  * Previously, you could document each parameter individually using JavaDoc, whereas packing them in an array makes this much trickier and hinders IDE suggestions
  * It could have a very small negative performance impact due to the need to allocate memory

If you still want to go this way, it might be advisable to add an assertion that the `Parameters` array has the correct length — ­as a safeguard, instead of letting the `IndexOutOfBoundsException` occur naturally.

**Comment by jaykay99992** [comment]
@edgarogh I just added the line `assert Parameters.length == 5 : "Parameters array must have a length of 5";` right after the line where the IO exception is thrown. Is it fine like this, do I merge it ? or should I just reject the whole pull request since it might impact performance negatively and also not very clear for other developers?

**Comment by edgarogh** [comment]
IMO there are no benefits to making this change and I'd reject the PR, but if you have a good reason to keep it as-is, it's probably good now that there's an assertion.

**Comment by jaykay99992** [comment]
@edgarogh In that case, I will reject the PR then to avoid complicating code. If you have any objection please let me know.

**Comment by jaykay9999** [comment]
Pull request rejected.

**Pull request closed without merging**
