### PR TITLE
Introduced a loop to create the buttons

### PR DESCRIPTION
**Pull request by jaykay99992**
Instead of adding each button manually with having the scaleFactor parameter as the only paramater changing, I introduced a loop that increases the scaleFactor in accordance to the existing code, without having to declare each button in a new line

### CODE REVIEW

**Review by diakhadija — CHANGES_REQUESTED** [review]
The loop approach is more concise and flexible and it avoids duplicating code for each zoom level. However you generates more buttons (16) than what you previously had (10). Consider seperating it in two loops, one with a 0.25 increment value (for zoomLevel between 0.25 and 1.5) and the second one with a 1 increment value (for zoomLevel between 2 and 4).

**Comment by jaykay99992** [comment]
@diakhadija I just updated the loop based on my understanding of your comment, can you verify and give me a decision to change it or merge it ?

**Review by diakhadija — APPROVED** [review]
perfect ! you can merge

**Comment by jaykay9999** [comment]
Sure, code merged

**Pull request merged**
